services:
  postgres:
    image: postgres
    volumes:
      - ./local/db.sql:/docker-entrypoint-initdb.d/01-db.sql
    environment:
      POSTGRES_PASSWORD: "@rock4me@"
    ports:
      - "5432:5432"
