services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "rock4me!!"
      POSTGRES_DB: "louvorappdb"
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: sh -c "npm run migration:up && npm run start:dev:docker"
    environment:
      DATABASE_NAME: "louvorappdb"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "rock4me!!"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      JWT_SECRET: "SECRET"
    ports:
      - "3000:80"
    volumes:
      - ./apps/api/src:/app/apps/api/src
    depends_on:
      postgres:o
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      VITE_USE_POLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules